PROMPT:
  - KEY: "CHANGE"
    LABEL: "Type of change"
    OPTIONS:
      - VALUE: "feat"
        DESC: "Add new feature"
      - VALUE: "fix"
        DESC: "A bug fix"
      - VALUE: "chore"
        DESC: "Add non bussiness logic change"
      - VALUE: "test"
        DESC: "Adding missing tests or correcting ones"
      - VALUE: "style"
        DESC: "A code change to improve clean code"
      - VALUE: "build"
        DESC: "Changes on build files and flows"
      - VALUE: "ci"
        DESC: "Changes on CI files"
      - VALUE: "refactor"
        DESC: "A code change"
      - VALUE: "docs"
        DESC: "Documentation changes"
  - KEY: "MODULE"
    LABEL: "Affected module"
  - KEY: "MESSAGE"
    LABEL: "Commit message"
  - KEY: "LABEL"
    LABEL: "Label"
    OPTIONS:
      - VALUE: ""
        DESC: "No label"
      - VALUE: "[CI SKIP]"
        DESC: "Skip continous integration pipeline"
      - VALUE: "[WIP]"
        DESC: "Work In Progress"
TEMPLATE: "{{CHANGE}}({{MODULE}}): {{MESSAGE}} {{LABEL}}"
